client_1:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_2:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_3:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_4:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_5:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_6:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_7:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_8:
  model:
    out_channels: 2
    task: graphClassification
  criterion:
    type: CrossEntropyLoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['error_rate']
    major_metric: 'error_rate'
client_9:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['mse']
    major_metric: 'mse'
client_10:
  model:
    out_channels: 10
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    optimizer:
      lr: 0.001
  grad:
    grad_clip: 1.0
  eval:
    metrics: ['mse']
    major_metric: 'mse'
client_11:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['mse']
    major_metric: 'mse'
client_12:
  model:
    out_channels: 1
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    optimizer:
      lr: 0.001
  eval:
    metrics: ['mse']
    major_metric: 'mse'
client_13:
  model:
    out_channels: 12
    task: graphRegression
  criterion:
    type: MSELoss
  train:
    optimizer:
      lr: 0.001
  grad:
    grad_clip: 1.0
  eval:
    metrics: ['mse']
    major_metric: 'mse'